### ISSUE TITLE
глобальные стили html, body

### ISSUE THREAD

**Issue by ExTeeP** [webtime-studio/create-html-boilerplate#2]
https://github.com/webtime-studio/create-html-boilerplate/blob/4860b3fe0816855a33241f93848b67299a0c87c5/source/scss/global.scss#L2

Привет, а для чего `body` вместе с `html` задавать `box-sizing`, если ниже в правилах указано

https://github.com/webtime-studio/create-html-boilerplate/blob/4860b3fe0816855a33241f93848b67299a0c87c5/source/scss/global.scss#L9

получается `box-sizing` в любом случае будет наследоваться от `html`.
Или в этом есть какой-то скрытый смысл?

**Comment by tinakuzmenko** [comment]
Да, действительно, можно обойтись без `body`.
Взяли в работу, исправим в следующем релизе. :)
