### ISSUE TITLE
Ошибки в консоли

### ISSUE THREAD

**Issue by Qwanead** [webtime-studio/create-html-boilerplate#36]
При запуке проекта сыплются ошибки в консоль.
При сборке ошибки остаются.
![image](https://user-images.githubusercontent.com/46837024/176672842-0d908c76-688c-4170-a965-096487da32dd.png)

Проверено в Windows, Ubuntu, Firefox, Chrome.

**Comment by ckomop0x** [comment]
Судя по всему проблема с `preload-webpack-plugin`, да и он порядком устарел.  Пока что я его удалю, так как нет смысла держать в проекте пакет, который уже 3 года не обновляется. 
@Qwanead, в вашем проекте я рекомендую просто удалить из `webpack` конфига:

```javascript
    new PreloadWebpackPlugin({
      rel: 'preload',
      include: 'allChunks', // or 'initial', or 'allAssets'
    }),
```    

Ну и соответсвенно из импорта и зависимостей. Проект от этого хуже работать не будет, просто уберётся некоторая опциональная функциональность.

P.S. Бойлерплейт я тоже обновлю на днях.

**Comment by Qwanead** [comment]
Удаление PreloadWebpackPlugin помогло. Ошибки пропали. @ckomop0x, спасибо за помощь.
